import type { Metadata } from 'next';

import { pretendard, roboto } from '@muroom/tailwind-config/fonts';

import BaseLayout from './_components/layout/base-layout';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko'>
      <body className={`${pretendard.className} ${roboto.className}`}>
        <BaseLayout>{children}</BaseLayout>
      </body>
    </html>
  );
}
