const BE_BASE_URL = process.env.NEXT_PUBLIC_BE_BASE_URL;

const NCP_CLIENT_ID = process.env.NEXT_PUBLIC_NCP_CLIENT_ID;
const NCP_CLIENT_SECRET = process.env.NEXT_PUBLIC_NCP_CLIENT_SECRET;

const KAKAO_REST_API_KEY = process.env.NEXT_PUBLIC_KAKAO_REST_API_KEY;
const KAKAO_CLIENT_ID = process.env.NEXT_PUBLIC_KAKAO_CLIENT_ID;
const KAKAO_CLIENT_SECRET = process.env.NEXT_PUBLIC_KAKAO_CLIENT_SECRET;
const KAKAO_REDIRECT_URI = process.env.NEXT_PUBLIC_KAKAO_REDIRECT_URI;

const NAVER_CLIENT_ID = process.env.NEXT_PUBLIC_NAVER_CLIENT_ID;
const NAVER_SECRET_KEY = process.env.NEXT_PUBLIC_NAVER_SECRET_KEY;
const NAVER_REDIRECT_URI = process.env.NEXT_PUBLIC_NAVER_REDIRECT_URI;

const GOOGLE_CLIENT_ID = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;
const GOOGLE_CLIENT_SECRET = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET;
const GOOGLE_REDIRECT_URI = process.env.NEXT_PUBLIC_GOOGLE_REDIRECT_URI;

export {
  BE_BASE_URL,
  NCP_CLIENT_ID,
  NCP_CLIENT_SECRET,
  KAKAO_REST_API_KEY,
  KAKAO_CLIENT_ID,
  KAKAO_CLIENT_SECRET,
  KAKAO_REDIRECT_URI,
  NAVER_CLIENT_ID,
  NAVER_SECRET_KEY,
  NAVER_REDIRECT_URI,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI,
};
