export const HIDE_EVENT_MODAL_UNTIL = 'HIDE_EVENT_MODAL_UNTIL';
export const AUTH_REDIRCT_STORE = 'AUTH_REDIRCT_STORE';
export const RECENT_KEYWORD_STORE = 'RECENT_KEYWORD_STORE';
export const LAST_LOGIN_PROVIDER = 'LAST_LOGIN_PROVIDER';
